
version: '3'

services:
  pg-0:
    image: misago_postgres
    #networks:
    #  - mm-in
    #volumes:
    #  - /nfs/mattermost/mattermost-84921-85098-pg-replica-0:/bitnami/postgresql
    environment:
      # Postgres administrator to access this node
      - POSTGRESQL_POSTGRES_PASSWORD=pgpool_postgres_password_secret
       # About the database
      - POSTGRESQL_USERNAME=mmuser
      - POSTGRESQL_PASSWORD=postgresql_password
      - POSTGRESQL_DATABASE=mattermost
      # Infos about replication
      - REPMGR_PASSWORD=postgresql_password
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      # Infos about this node
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
      # Telegraf
      - INFLUX_DB_LOCATION=http://10.5.0.109:8086
      - INFLUX_DB_NAME=telegraf
      - HOST_MONITORING_TAG=postgres0-
      # ELK
      - ELASTIC_SEARCH_HOSTS=["10.5.0.109:9200"]
    #secrets:
    #  - pgpool_postgres_password_secret
    #  - postgresql_password

  pg-1:
    image:  misago_postgres
    #networks:
    #  - mm-in
    #volumes:
    #  - /nfs/mattermost/mattermost-84921-85098-pg-replica-1:/bitnami/postgresql
    environment:
      # Postgres administrator to access this node
      - POSTGRESQL_POSTGRES_PASSWORD=pgpool_postgres_password_secret
      # About the database
      - POSTGRESQL_USERNAME=mmuser
      - POSTGRESQL_PASSWORD=postgresql_password
      - POSTGRESQL_DATABASE=mattermost
      # Infos about replication
      - REPMGR_PASSWORD=postgresql_password
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      # Infos about this node
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1   
      # Telegraf
      - INFLUX_DB_LOCATION=http://10.5.0.109:8086
      - INFLUX_DB_NAME=telegraf
      - HOST_MONITORING_TAG=postgres1-
      # ELK
      - ELASTIC_SEARCH_HOSTS=["10.5.0.109:9200"]
    #secrets:
    #  - pgpool_postgres_password_secret
    #  - postgresql_password

  pg-2:
    image: misago_postgres
    #networks:
    #  - mm-in
    #volumes:
    #  - /nfs/mattermost/mattermost-84921-85098-pg-replica-2:/bitnami/postgresql
    environment:
      # Postgres administrator to access this node
      - POSTGRESQL_POSTGRES_PASSWORD=pgpool_postgres_password_secret
      # About the database
      - POSTGRESQL_USERNAME=mmuser
      - POSTGRESQL_PASSWORD=postgresql_password
      - POSTGRESQL_DATABASE=mattermost
      # Infos about replication
      - REPMGR_PASSWORD=postgresql_password
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1,pg-2
      # Infos about this node
      - REPMGR_NODE_NAME=pg-2
      - REPMGR_NODE_NETWORK_NAME=pg-2
      # Telegraf
      - INFLUX_DB_LOCATION=http://10.5.0.109:8086
      - INFLUX_DB_NAME=telegraf
      - HOST_MONITORING_TAG=postgres2-
      # ELK
      - ELASTIC_SEARCH_HOSTS=["10.5.0.109:9200"]

  pgpool:
    image: bitnami/pgpool:4.1.1
    #networks:
    #  - mm-in
    ports:
      - "6320:5432"
    environment:
      # Comma separated list of backend nodes in the cluster.
      - PGPOOL_BACKEND_NODES=0:pg-0:5432,1:pg-1:5432,2:pg-2:5432
      # Information for perfoming streaming checks.
      - PGPOOL_SR_CHECK_USER=mmuser
      - PGPOOL_SR_CHECK_PASSWORD=postgresql_password
      # Whether to enable LDAP authentication.
      - PGPOOL_ENABLE_LDAP=no
      # Postgres administrator credentials, this will be use to allow postgres admin authentication through Pgpool.
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=pgpool_postgres_password_secret
      # Credentials for the pgpool administrator
      - PGPOOL_ADMIN_USERNAME=admin
      - PGPOOL_ADMIN_PASSWORD=pgpool_postgres_password_secret
      # Load balancing
      - PGPOOL_ENABLE_LOAD_BALANCING=yes
    depends_on:
      - pg-0
      - pg-1
      - pg-2
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    #deploy:
    #  replicas: 3
